### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException: leiningen.core.project$reduce_repo_step

### ISSUE THREAD

**Issue by eklipse2k8** [weavejester/lein-ring#171]
Not sure what changed, but every time I run

lein ring server-headless

I'm getting this exception.

```java
Exception in thread "main" java.lang.ClassNotFoundException: leiningen.core.project$reduce_repo_step, compiling:(/private/var/folders/6d/0jn0yd615330kltbpykxtyywsm26m3/T/form-init1803805135283065499.clj:1:18243)
	at clojure.lang.Compiler.load(Compiler.java:7234)
	at clojure.lang.Compiler.loadFile(Compiler.java:7165)
	at clojure.main$load_script.invoke(main.clj:275)
	at clojure.main$init_opt.invoke(main.clj:280)
	at clojure.main$initialize.invoke(main.clj:308)
	at clojure.main$null_opt.invoke(main.clj:343)
	at clojure.main$main.doInvoke(main.clj:421)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: java.lang.ClassNotFoundException: leiningen.core.project$reduce_repo_step
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at clojure.lang.DynamicClassLoader.findClass(DynamicClassLoader.java:69)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at clojure.lang.DynamicClassLoader.loadClass(DynamicClassLoader.java:77)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at clojure.lang.RT.classForName(RT.java:2154)
	at clojure.lang.RT.classForName(RT.java:2163)
	at clojure.lang.LispReader$EvalReader.invoke(LispReader.java:1120)
	at clojure.lang.LispReader$DispatchReader.invoke(LispReader.java:691)
	at clojure.lang.LispReader.read(LispReader.java:263)
	at clojure.lang.LispReader.readDelimitedList(LispReader.java:1200)
	at clojure.lang.LispReader$MapReader.invoke(LispReader.java:1158)
	at clojure.lang.LispReader.read(LispReader.java:263)
	at clojure.lang.LispReader.readDelimitedList(LispReader.java:1200)
	at clojure.lang.LispReader$ListReader.invoke(LispReader.java:1049)
	at clojure.lang.LispReader.read(LispReader.java:263)
	at clojure.lang.LispReader.read(LispReader.java:200)
	at clojure.lang.LispReader.access$200(LispReader.java:40)
	at clojure.lang.LispReader$EvalReader.invoke(LispReader.java:1104)
	at clojure.lang.LispReader$DispatchReader.invoke(LispReader.java:691)
	at clojure.lang.LispReader.read(LispReader.java:263)
	at clojure.lang.LispReader.read(LispReader.java:200)
	at clojure.lang.LispReader.access$200(LispReader.java:40)
	at clojure.lang.LispReader$MetaReader.invoke(LispReader.java:792)
	at clojure.lang.LispReader.read(LispReader.java:263)
	at clojure.lang.LispReader.readDelimitedList(LispReader.java:1200)
	at clojure.lang.LispReader$MapReader.invoke(LispReader.java:1158)
	at clojure.lang.LispReader.read(LispReader.java:263)
	at clojure.lang.LispReader.read(LispReader.java:200)
	at clojure.lang.LispReader.access$200(LispReader.java:40)
	at clojure.lang.LispReader$MetaReader.invoke(LispReader.java:800)
	at clojure.lang.LispReader.read(LispReader.java:263)
	at clojure.lang.LispReader.readDelimitedList(LispReader.java:1200)
	at clojure.lang.LispReader$MapReader.invoke(LispReader.java:1158)
	at clojure.lang.LispReader.read(LispReader.java:263)
	at clojure.lang.LispReader.readDelimitedList(LispReader.java:1200)
	at clojure.lang.LispReader$ListReader.invoke(LispReader.java:1049)
	at clojure.lang.LispReader.read(LispReader.java:263)
	at clojure.lang.LispReader.read(LispReader.java:200)
	at clojure.lang.LispReader.access$200(LispReader.java:40)
	at clojure.lang.LispReader$EvalReader.invoke(LispReader.java:1104)
	at clojure.lang.LispReader$DispatchReader.invoke(LispReader.java:691)
	at clojure.lang.LispReader.read(LispReader.java:263)
	at clojure.lang.LispReader.read(LispReader.java:200)
	at clojure.lang.LispReader.access$200(LispReader.java:40)
	at clojure.lang.LispReader$MetaReader.invoke(LispReader.java:792)
	at clojure.lang.LispReader.read(LispReader.java:263)
	at clojure.lang.LispReader.readDelimitedList(LispReader.java:1200)
	at clojure.lang.LispReader$ListReader.invoke(LispReader.java:1049)
	at clojure.lang.LispReader.read(LispReader.java:263)
	at clojure.lang.LispReader.readDelimitedList(LispReader.java:1200)
	at clojure.lang.LispReader$ListReader.invoke(LispReader.java:1049)
	at clojure.lang.LispReader.read(LispReader.java:263)
	at clojure.lang.LispReader.readDelimitedList(LispReader.java:1200)
	at clojure.lang.LispReader$ListReader.invoke(LispReader.java:1049)
	at clojure.lang.LispReader.read(LispReader.java:263)
	at clojure.lang.LispReader.read(LispReader.java:196)
	at clojure.lang.Compiler.load(Compiler.java:7222)
	... 11 more
Subprocess failed

```

**Comment by MichaelBlume** [comment]
Did you by any chance upgrade your Leiningen install recently?

**Comment by eklipse2k8** [comment]
@MichaelBlume I deleted and reinstalled leiningen yesterday to see if something became corrupt. :(

**Comment by jtbeckha** [comment]
Looking the leiningen release notes (https://github.com/technomancy/leiningen/releases) it looks like they had a plugin related bug in the 2.6.0 release.  I ran into the same problem on 2.6.0, resolved it by upgrading to 2.6.1

**Comment by sickill** [comment]
I confirm upgrading to 2.6.1 fixes the problem.
