### ISSUE TITLE
uberwar weblogic 12.1.3

### ISSUE THREAD

**Issue by ouvanous** [weavejester/lein-ring#181]
Hi, 

I cannot create a war file that work with weblogic. 
Is there somewhere a working example project. 
When i don't put the weblogic.xml i have this error : 

Error 500--Internal Server Error

java.lang.IllegalStateException: Attempting to call unbound fn: #'test1.servlet/service-method
	at clojure.lang.Var$Unbound.throwArity(Var.java:43)
	at clojure.lang.AFn.invoke(AFn.java:40)
	at test1.servlet$_service.invokeStatic(servlet.clj:1)
	at test1.servlet$_service.invoke(servlet.clj:1)
	at test1.servlet.service(Unknown Source)
	at weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run(StubSecurityHelper.java:280)
	at weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run(StubSecurityHelper.java:254)
	at weblogic.servlet.internal.StubSecurityHelper.invokeServlet(StubSecurityHelper.java:136)
	at weblogic.servlet.internal.ServletStubImpl.execute(ServletStubImpl.java:346)
	at weblogic.servlet.internal.ServletStubImpl.execute(ServletStubImpl.java:243)
	at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.wrapRun(WebAppServletContext.java:3432)
	at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.run(WebAppServletContext.java:3402)
	at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:321)
	at weblogic.security.service.SecurityManager.runAs(SecurityManager.java:120)
	at weblogic.servlet.provider.WlsSubjectHandle.run(WlsSubjectHandle.java:57)
	at weblogic.servlet.internal.WebAppServletContext.doSecuredExecute(WebAppServletContext.java:2285)
	at weblogic.servlet.internal.WebAppServletContext.securedExecute(WebAppServletContext.java:2201)
	at weblogic.servlet.internal.WebAppServletContext.execute(WebAppServletContext.java:2179)
	at weblogic.servlet.internal.ServletRequestImpl.run(ServletRequestImpl.java:1572)
	at weblogic.servlet.provider.ContainerSupportProviderImpl$WlsRequestExecutor.run(ContainerSupportProviderImpl.java:255)
	at weblogic.work.ExecuteThread.execute(ExecuteThread.java:311)
	at weblogic.work.ExecuteThread.run(ExecuteThread.java:263)

With it : 

Error 403--Forbidden

From RFC 2068 Hypertext Transfer Protocol -- HTTP/1.1:

10.4.4 403 Forbidden

The server understood the request, but is refusing to fulfill it. Authorization will not help and the request SHOULD NOT be repeated. If the request method was not HEAD and the server wishes to make public why the request has not been fulfilled, it SHOULD describe the reason for the refusal in the entity. This status code is commonly used when the server does not wish to reveal exactly why the request has been refused, or when no other response is applicable.

I don' t know where to go ? 
Many thanks in advance for any information 

Samuel

**Comment by weavejester** [comment]
Can you provide some code? For instance, an example project that fails on weblogic? Does the example project succeed on other servlet containers, like Tomcat?

**Comment by ouvanous** [comment]
Hi James and many thanks to have a look at this. 
Here is a repository that work with tomcat but create an error with weblogic: https://github.com/ouvanous/test1
Thanks, 
Samuel

**Comment by MichaelBlume** [comment]
I don't have a lot of bandwidth right now, but if you can tell me how I can quickly get weblogic running on my Ubuntu laptop (Ideally without setting up an Oracle login?), I'll be happy to poke around at this
