### ISSUE TITLE
0.12.2 fails when compiling `:aot :all`

### ISSUE THREAD

**Issue by jeaye** [weavejester/lein-ring#198]
I end up seeing this:

```text
$ lein ring uberjar
Compiling :all
Could not locate all__init.class or all.clj on classpath.
Exception in thread "main" java.io.FileNotFoundException: Could not locate all__init.class or all.clj on classpath., compiling:(/tmp/form-init8182751785800392298.clj:1:73)
	at clojure.lang.Compiler.load(Compiler.java:7526)
	at clojure.lang.Compiler.loadFile(Compiler.java:7452)
	at clojure.main$load_script.invokeStatic(main.clj:278)
	at clojure.main$init_opt.invokeStatic(main.clj:280)
	at clojure.main$init_opt.invoke(main.clj:280)
	at clojure.main$initialize.invokeStatic(main.clj:311)
	at clojure.main$null_opt.invokeStatic(main.clj:345)
	at clojure.main$null_opt.invoke(main.clj:342)
	at clojure.main$main.invokeStatic(main.clj:424)
	at clojure.main$main.doInvoke(main.clj:387)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:702)
	at clojure.main.main(main.java:37)
Caused by: java.io.FileNotFoundException: Could not locate all__init.class or all.clj on classpath.
	at clojure.lang.RT.load(RT.java:463)
	at clojure.lang.RT.load(RT.java:426)
	at clojure.core$load$fn__6548.invoke(core.clj:6046)
	at clojure.core$load.invokeStatic(core.clj:6045)
	at clojure.core$load.doInvoke(core.clj:6029)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5848)
	at clojure.core$compile$fn__6553.invoke(core.clj:6056)
	at clojure.core$compile.invokeStatic(core.clj:6056)
	at clojure.core$compile.invoke(core.clj:6048)
	at user$eval164$fn__173.invoke(form-init8182751785800392298.clj:1)
	at user$eval164.invokeStatic(form-init8182751785800392298.clj:1)
	at user$eval164.invoke(form-init8182751785800392298.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7062)
	at clojure.lang.Compiler.eval(Compiler.java:7052)
	at clojure.lang.Compiler.eval(Compiler.java:7052)
	at clojure.lang.Compiler.load(Compiler.java:7514)
	... 12 more
Compilation failed: Subprocess failed
```

The solution is to downgrade to 0.12.1.

**Comment by MichaelBlume** [comment]
Ok, this is interesting. The canonical form for the lein internals is {:aot [:all]} but the tutorial/sample project suggests {:aot :all}. Looks like we should catch both.

**Comment by jeaye** [comment]
Ah, I see. Thanks for digging into it, @MichaelBlume.

**Comment by MichaelBlume** [comment]
I may get a point release out with a fix, but the laptop I'd normally deploy from isn't with me. If you want, you can build from master and see if that solves the problem.

**Comment by jeaye** [comment]
Happy new year! Building from master does the trick for me. Thank you! Looking forward to that release going up.

**Comment by MichaelBlume** [comment]
Deployed =)
